### ISSUE TITLE
Try again button on no connectivity 

### ISSUE THREAD

**Issue by pg8wood** [cjbvt/SpareME#79]
Currently, on loss of connectivity, the app softlocks on the "no connectivity" screen. It would be great to have a "reload" or "try again" button instead of having to reload the app.

**Comment by benbrott** [comment]
The app listens for changes in connectivity so the no connectivity screen goes away when connection comes back @pg8wood

**Comment by pg8wood** [comment]
Dunno why I didn't see this earlier, but it works now
